accounts/urls.py
from accounts.views import (AccountChangePasswordView,
                            AccountCreateView,
                            AccountLoginView,
                            AccountLogoutView,
                            AccountUpdateView)

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('password/', AccountChangePasswordView.as_view(), name='password'),
]

core/urls.py
from core.views import index

from django.urls import path


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    ]

gogitsite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('notes/', include('notes.urls')),
    path('', include('core.urls')),
    path('', include('notes.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name = 'notes'
urlpatterns = [
	# path('', views.index, name='index'),
	path('repositories', views.RepositoryListView.as_view(), name='repositories'),
	path('usernotes', views.NoteListView.as_view(), name='notes'),
	]

accounts/models.py
from django.db import models

# Create your models here.

notes/models.py
import datetime

from django.db import models


class Repository(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=1000, null=True)


class Note(models.Model):
    text = models.CharField(max_length=1000, null=False)
    repo = models.CharField(max_length=200, null=True)
    file_path = models.CharField(max_length=200, null=True)
    line = models.SmallIntegerField(null=True)
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)


class UserNote(models.Model):
    text = models.CharField(max_length=1000, null=False)
    creation_time = models.CharField(max_length=64, null=True, default=datetime.date.today)

usernotes/models.py
import datetime

from django.db import models


class UserNote(models.Model):
    text = models.CharField(max_length=1000, null=False)
    creation_time = models.CharField(max_length=64, null=True, default=datetime.date.today)

accounts/forms.py
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm


class AccountCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'first_name', 'last_name']


class AccountUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountEdinPasswordForm(PasswordChangeForm):
    pass

notes/forms.py
from django import forms

from notes.models import UserNote


class UserNoteCreateForm(forms.ModelForm):
    class Meta:
        model = UserNote
        fields = '__all__'

usernotes/forms.py
from django import forms

from usernotes.models import UserNote


class UserNoteCreateForm(forms.ModelForm):
    class Meta:
        model = UserNote
        fields = '__all__'

accounts/views.py
from accounts.forms import AccountCreateForm, AccountEdinPasswordForm, AccountUpdateForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView


class AccountCreateView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('core:index')


class AccountLoginView(LoginView):
    template_name = 'login.html'

    def get_redirect_url(self):
        return reverse('core:index')


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def get_redirect_url(self):
        return reverse('core:index')


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'profile.html'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('core:index')

    def get_object(self, queryset=None):
        return self.request.user


class AccountChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    form_class = AccountEdinPasswordForm
    template_name = 'change-password.html'
    success_url = reverse_lazy('accounts:profile')

core/views.py
from django.shortcuts import render


def index(request):
    return render(
        request=request,
        template_name='index.html'
    )

notes/views.py
from django.shortcuts import render
from django.views.generic import ListView

from .models import Note, Repository


# def index(request):
# 	return render(request, 'index.html', {})


class NoteListView(ListView):
	model = Note


class RepositoryListView(ListView):
	model = Repository

usernotes/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/change-password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
      <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-info" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>

    </form>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
      <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-info" type="submit" value="Log in">
        <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>

    </form>
{% endblock %}

accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

    <a class="btn btn-light" href="{% url 'accounts:login' %}">Login</a>
    <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>

{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
      <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-info" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>

    </form>
{% endblock %}

accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
      <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-info" type="submit" value="Register">
        <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>

    </form>
{% endblock %}

notes/templates/nav.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">   
    <title>{% block title %}ToDoGit{% endblock %} </title>
  </head>
  <body>

<div class='container'>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'notes:index' %}">ToDoGit</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'notes:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
         <a class="nav-link" href="{% url 'notes:repositories' %}">Repositories</a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'notes:notes' %}">Notes</a>
      </li>
       
      
     
      <li class="nav-item active">
        {% if user.is_authenticated %}{{ user.username }}{% else %}<a class="nav-link" href="" tabindex="-1">Вход{% endif %}</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="" method="GET" >
      <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</div>

notes/templates/notes/note_list.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

notes/templates/notes/repository_list.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

templates/base.html
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% include 'nav.html' %}


<div class="container">
  {% block content %} {% endblock %}
</div>


{% include 'footer.html' %}

templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="">ToDoGit</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/index.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

templates/nav.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">   
    <title>{% block title %}ToDoGit{% endblock %} </title>
  </head>
  <body>

<div class='container'>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'core:index' %}">ToDoGit</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
         <a class="nav-link" href="{% url 'notes:repositories' %}">Repositories</a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'notes:notes' %}">Notes</a>
      </li>
       
      
     
      <li class="nav-item active">
        {% if user.is_authenticated %}{{ user.username }}{% else %}<a class="nav-link" href="" tabindex="-1">Вход{% endif %}</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="" method="GET" >
      <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</div>